---
repos:
  - repo: https://github.com/gracig/pre-commit-actions
    rev: 698145588511b23008aaa2ca088c96cff5443fd0
    hooks:
      - id: check-yaml
  - repo: https://github.com/gracig/pre-commit-actions
    rev: 698145588511b23008aaa2ca088c96cff5443fd0
    hooks:
      - id: gen-github-actions-doc
        files: \.github/workflows/main\.yaml
