name: 'bbw-rust'
description: 'Build Rust Programs'
inputs:
  working-directory:
    description: 'The working directory to run the commands'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: Configure rust cache
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: "${{ inputs.working-directory }}"
    - name: Run tests
      run: cargo test
      working-directory: "${{ inputs.working-directory }}"
    - name: Build
      run: cargo build --release
      working-directory: "${{ inputs.working-directory }}"
